# config.yaml
# Configuration for PPO CarRacing training

# --- General Env ---
env_name: "CarRacing-v3"
n_stack: 8

# --- Training Parameters ---
train:
  algo: "PPO"
  n_envs: 6 # Default number of parallel environments
  n_steps: 1000 #Â number of steps to do in an environment
  batch_size: 1024
  total_timesteps: 2000000
  fr_tau_penalty: 0.001
  ent_coef: 0.01

# --- Logging & Saving ---
logging:
  log_dir: "./logs/"
  name_prefix: "ppo_carracing_latest"
  checkpoint_save_freq: 10000 # OverwriteCheckpointCallback save frequency

# --- Visualization ---
visualize:
  video_folder: "videos/"
